[package]
name = "sudoku"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.204"
serde_json = "1.0.122"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "my_benchmark"
harness = false
